
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/deanishe/awgo"
  version = "0.13.2"

[[constraint]]
  name = "github.com/docopt/docopt.go"
  # version = "0.6.2"
  revision = "ee0de3bc6815ee19d4a46c7eb90f829db0e014b1"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.2"

# [[override]]
#   name = "github.com/docopt/docopt-go"
#   revision = "ee0de3bc6815ee19d4a46c7eb90f829db0e014b1"
